// Generated by CoffeeScript 1.5.0
(function() {
  var app, compile, express, routes, stylus;

  express = require('express');

  stylus = require('stylus');

  app = exports.app = express();

  compile = function(str, path) {
    return stylus(str).set('filename', path);
  };

  app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(stylus.middleware({
      src: __dirname + '/public',
      compile: compile
    }));
    return app.use(express["static"](__dirname + '/public'));
  });

  routes = require('./routes/routes');

  app.get('/', routes.index);

  app.listen(3000);

  console.log("listening on port 3000...");

}).call(this);
